version: '3.8'

services:
  pollify:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOSTNAME: db
      DB_PORT: 5432
      DB_DATABASE: pollify
      DB_USER: postgres
      DB_PASS: 123
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pollify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
